export const PH_LOCATIONS = [
  { region: "NCR", label: "Metro Manila", cities: ["Quezon City", "Manila", "Makati", "Pasig", "Taguig", "Marikina", "Caloocan", "Pasay", "Parañaque", "Las Piñas", "Muntinlupa", "Valenzuela", "Malabon", "Mandaluyong", "San Juan", "Navotas", "Pateros"] },
  { region: "Region I", label: "Ilocos Region", cities: ["Vigan", "Laoag", "San Fernando (La Union)", "Dagupan"] },
  { region: "Region II", label: "Cagayan Valley", cities: ["Tuguegarao", "Cauayan", "Santiago"] },
  { region: "Region III", label: "Central Luzon", cities: ["San Fernando (Pampanga)", "Angeles", "Olongapo", "Malolos", "Cabanatuan", "Tarlac City"] },
  { region: "Region IV-A", label: "CALABARZON", cities: ["Antipolo", "Lucena", "Calamba", "Batangas City", "Lipa", "Cavite City", "Tagaytay"] },
  { region: "Region V", label: "Bicol Region", cities: ["Legazpi", "Naga", "Sorsogon City", "Tabaco"] },
  { region: "Region VI", label: "Western Visayas", cities: ["Iloilo City", "Bacolod", "Roxas City"] },
  { region: "Region VII", label: "Central Visayas", cities: ["Cebu City", "Lapu-Lapu", "Mandaue", "Tagbilaran", "Dumaguete"] },
  { region: "Region VIII", label: "Eastern Visayas", cities: ["Tacloban", "Ormoc", "Calbayog"] },
  { region: "Region IX", label: "Zamboanga Peninsula", cities: ["Zamboanga City", "Pagadian", "Dipolog"] },
  { region: "Region X", label: "Northern Mindanao", cities: ["Cagayan de Oro", "Iligan", "Malaybalay", "Valencia"] },
  { region: "Region XI", label: "Davao Region", cities: ["Davao City", "Tagum", "Digos", "Panabo"] },
  { region: "Region XII", label: "SOCCSKSARGEN", cities: ["Koronadal", "General Santos", "Kidapawan", "Cotabato City"] },
  { region: "Region XIII", label: "Caraga", cities: ["Butuan", "Surigao City", "Bislig"] },
  { region: "BARMM", label: "Bangsamoro", cities: ["Cotabato City", "Marawi", "Lamitan"] },
  { region: "CAR", label: "Cordillera", cities: ["Baguio", "Tabuk", "La Trinidad"] },
  { region: "MIMAROPA", label: "MIMAROPA", cities: ["Puerto Princesa", "Calapan", "Romblon"] },
];
